/*
 * Copyright (C) 2026 Savoir-faire Linux Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA.
 */

// Generated by generate_constants.py — do not edit manually.
// Edit event_names.json at the workspace root and re-run the script.

#if DEBUG_TOOLS_ENABLED

public enum SpanName {
    public static let messageSend                   = "message.send"
    public static let messageReceived               = "message.received"
    public static let pushReceived                  = "push.received"
    public static let pushReceiveInApp              = "push.receive-in-app"
    public static let pushSkipped                   = "push.skipped"
    public static let pushResubscribe               = "push.resubscribe"
    public static let pushFinished                  = "push.finished"
    public static let pushTimeout                   = "push.timeout"
    public static let pushStreamStarted             = "push.stream.started"
    public static let pushStreamEmpty               = "push.stream.empty"
    public static let pushStreamError               = "push.stream.error"
    public static let pushStreamDataReceived        = "push.stream.data_received"
    public static let pushPayloadDecrypted          = "push.payload.decrypted"
    public static let pushDaemonStarted             = "push.daemon.started"
    public static let pushNotificationPresented     = "push.notification.presented"
    public static let pushCallReported              = "push.call.reported"
    public static let pushEventMessage              = "push.event.message"
    public static let pushEventFileTransferDone     = "push.event.file_transfer.done"
    public static let pushEventFileTransferProgress = "push.event.file_transfer.progress"
    public static let pushEventSyncCompleted        = "push.event.sync.completed"
    public static let pushEventConversationCloned   = "push.event.conversation.cloned"
    public static let pushEventInvitation           = "push.event.invitation"
    public static let pushEventActiveCall           = "push.event.active_call"
}

#endif
