disabled_rules: # rule identifiers to exclude from running
  - todo
  - closure_parameter_position

opt_in_rules: # some rules are only opt-in
  - closure_spacing # can be autocorrected
  - closure_end_indentation
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - unused_import
  - explicit_self
  - modifier_order
  - toggle_bool
  - empty_count # can't be autocorrected
  - multiline_function_chains
  - closing_brace_spacing
  - closure_body_length
  - unused_declaration
  - vertical_parameter_alignment_on_call
  - collection_alignment
  - identical_operands
  - let_var_whitespace
  - attributes
  - lower_acl_than_parent
  - strict_fileprivate
  - overridden_super_call
  #- unowned_variable_capture

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Ring/Constants
  - WhirlyGlobeMaply

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

closure_body_length:
  - 60 # warning
  - 80 # error

type_body_length:
  - 300 # warning
  - 400 # error

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string

identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)

function_body_length:
  - 75
  - 100

file_length:
  warning: 600
  error: 1200

line_length:
  warning: 200
  error: 250
