# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'Ring' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ring
  pod 'expanding-collection'

  target 'RingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
